alias ls='ls -h --color=auto'
alias sd="shutdown now"
alias wifi="nmtui connect"
alias clipboard="xclip -selection clipboard"
alias todo="code ~/Documents/Other/todo.md "
alias keybinds="code /home/kb/Documents/Projects/linux_utils/manuals/keybinds.md"
alias commands="code /home/kb/Documents/Projects/linux_utils/manuals/commands.md"
alias locations="code /home/kb/Documents/Projects/linux_utils/manuals/locations.md"
alias nau="wine /home/kb/Documents/MIEI/4_Grade/1_Sem/VI1/nau_bin/composer.exe"
alias minecraft="prime-run /opt/minecraft-launcher/minecraft-launcher"
alias py="python"
alias py3="python3"
alias manuals="manual -l"
alias mk="make"
alias dt="date \"+%a %d %b | %H:%M\""
alias fonts="fc-list | awk -F: '{print $2}'"
alias ff="firefox-developer-edition"
alias weather="curl -s wttr.in | head -17"alias cb="clipboard"
alias ranger=". ranger"
alias calendar="calcurse"