alias sd="shutdown now"
alias wifi="nmtui connect"
alias clipboard="xclip -selection clipboard"
alias todo="code ~/Documents/Other/todo.md "
alias keybinds="code /home/kb/Documents/Projects/linux_utils/manuals/keybinds.md"
alias commands="code /home/kb/Documents/Projects/linux_utils/manuals/commands.md"
alias nau="/home/kb/Documents/MIEI/4_Grade/1_Sem/VI1/nauv0.2.0/composer.exe"
alias nau="wine /home/kb/Documents/MIEI/4_Grade/1_Sem/VI1/nauv0.2.0/composer.exe"
