colors:
  primary:
    background: '0x222222'
    foreground: '0xeaeaea'

  # Normal colors
  normal:
    black:   '0x1b1918'
    red:     '0xf22c40'
    green:   '0x5ab738'
    yellow:  '0xd5911a'
    blue:    '0x407ee7'
    magenta: '0x6666ea'
    cyan:    '0x70c0ba'
    white:   '0xeaeaea'

  # Bright colors
  bright:
    black:   '0x766e66'
    red:     '0xff3334'
    green:   '0x9ec400'
    yellow:  '0xe7c547'
    blue:    '0x7aa6da'
    magenta: '0xb77ee0'
    cyan:    '0x00ad9c'
    white:   '0xffffff'